language: python

sudo: required

os: linux

arch: ppc64le

python:
  - "3.6"

script:
  - sudo apt-get install python3-pip
  - pip3 install pylint virtualenv
  - ./dev build
  - ./dev install
  - cpi --help
